In [1]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import TruncatedSVD
from scipy.sparse import csr_matrix
from sklearn import datasets
import numpy as np

In [2]:
digits = datasets.load_digits()
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [4]:
X = StandardScaler().fit_transform(digits.data)
X_sparse = csr_matrix(X)
print(X_sparse)

  (0, 1)	-0.3350164872543856
  (0, 2)	-0.04308101770538793
  (0, 3)	0.2740715207154218
  (0, 4)	-0.6644775126361527
  (0, 5)	-0.8441293865949171
  (0, 6)	-0.40972392088346243
  (0, 7)	-0.1250229232970408
  (0, 8)	-0.05907755711884675
  (0, 9)	-0.6240092623290964
  (0, 10)	0.4829744992519545
  (0, 11)	0.7596224512649244
  (0, 12)	-0.05842586308220443
  (0, 13)	1.1277211297338117
  (0, 14)	0.8795830595483867
  (0, 15)	-0.13043338063115095
  (0, 16)	-0.04462507326885248
  (0, 17)	0.11144272449970435
  (0, 18)	0.8958804382797294
  (0, 19)	-0.8606663175537699
  (0, 20)	-1.1496484601880896
  (0, 21)	0.5154718747277965
  (0, 22)	1.905963466976408
  (0, 23)	-0.11422184388584329
  (0, 24)	-0.03337972630405602
  (0, 25)	0.48648927722411006
  :	:
  (1796, 38)	-0.8226945146290309
  (1796, 40)	-0.061343668908253476
  (1796, 41)	0.8105536026095989
  (1796, 42)	1.3950951873625397
  (1796, 43)	-0.19072005925701047
  (1796, 44)	-0.5868275383619802
  (1796, 45)	1.3634658076459107
  (1796, 46)	0.58749033

In [8]:
tsvd = TruncatedSVD(n_components=X_sparse.shape[1]-2)
X_tsvd = tsvd.fit(X)
print(X_tsvd)

TruncatedSVD(algorithm='randomized', n_components=62, n_iter=5,
       random_state=None, tol=0.0)


In [9]:
tsvd_var_ratios = tsvd.explained_variance_ratio_

In [10]:
def feature_selection_svd(var_ratio, goal_var: float) -> int:
    # Set initial varience to 0
    total_var = 0.0
    # Set the initial number of features
    n_components = 0
    
    # For the explained variance of each feature:
    for exp_var in var_ratio:
        total_var += exp_var
        n_components += 1
        if total_var >= goal_var:
            break
    return n_components

In [11]:
#Set the goal_variance to 0.9 and return the number of components that pass through the threshhold
feature_selection_svd(tsvd_var_ratios, 0.9)

31